language: node_js
node_js:
- '4'
- '6'
install:
- npm install
script:
- npm run lint
notifications:
  slack:
    rooms:
      secure: zNYhXX/Ug2TyivToprkpXRlj6SVSN938pY0rDPjR7VSS0HuNCF6G3wL9fyMQBI0rmlFHXgYvGrGLxacg8m76JPxl1blUftKjcAjMTWw/S3IzzBMLR11JsZEtmWAMfOagbmDWV13kKbaL6KdN1K8eFJgPyWob3mhNJ4wEgdHsSOgMKRljPf6f0P5sQW6O4AYGiODb5Ay2NtjYVz+CPyblUhenVhM4bG2YmRfIvbq1Yhfqh/BJS1EGszVBZahHvteMp+T5Bu3KHKQox4niaOxlBdXlC5FyjM3EjFPJDwgQ614Yu0a/uCew5Uvax7/7LjLgTFfbTijd91scJ4TOBFKilSXRRLv+1tKFGqL4NMDpqSz0fzcUrG+phk6pe2kCC7e8FGd5VZgrVoVKJGlsA5i1b1byWIGH7wL3Q+mH/GFpOYJMVXDtIwTU8PIsICOeHP6GW36l4hC6B3YJ4Q7of/6wVraIwEywTJG8RFlDXP8mXISUsZDGigT3uMceYYT+pQc69AaxuKhXSfpBAOQDAEvQp/tCQqyJilPk8jD/fnhG28jvIzgSH6ChRPLqiGYk41j1twqEbAODVG0Cg4fEjyq6z3k/5Dj3csjTx7S8iMxidZ+K4wOdVoFKtjDI4ZDLZa0FmMpxuVwzWq+VMwjddagPwLM26BQFlSKJ6IU0lFqWm6c=
    on_success: change
    on_failure: always
  email: false
